project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  description: "Up, up and away!"
  
  twitter-card:
    creator: "@onlinecape"
    
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "{{< fa house-user >}} Home"
      - href: about.qmd
        text: "{{< fa address-card >}} About"
      - href: CV_2022.pdf
        text: "{{< fa paperclip >}} Vitae"
      - href: mailto:shreyas.meher@utdallas.edu
        text: "{{< fa paper-plane >}} Contact"
      - section: "{{< fa blog >}} Assignments"
        contents:
          - href: "assignments/labs/lab.qmd"
            text: Lab Assignments
          - href: "assignments/a2/a2.qmd"
            text: Assignment 2
          - href: "assignments/a3/a3.qmd"
            text: Assignment 3
          - href: "assignments/a4/a4.qmd"
            text: Assignment 4
          - href: "assignments/a5/a5.qmd"
            text: Assignment 5
          - href: "assignments/a6/a6.qmd"
            text: Assignment 6          
          - href: "assignments/a8/a8.qmd"
            text: Assignment 8
          - href: "assignments/taiwan-talk/taiwan.qmd"
            text: Taiwan Talk - Cunningham
          - href: "assignments/proposal/prop-2-22-23.qmd"
            text: Project Proposal
      - icon: linkedin
        href: https://www.linkedin.com/in/shreyasmeher/
      - icon: twitter
        href: https://twitter.com/Onlinecape
      - icon: github
        href: https://github.com/shreyasmeher
      - section: "{{< fa diagram-project >}} Projects"
        contents:
          - href: "projects/BLScraper/bls.html"
            text: BLScraper
          - href: "projects/CPU/CPU.html"
            text: CPU Usage Monitor

  page-footer: 
    left: "© 2023 Shreyas Meher"
    
format:
  html:
    theme:
      light: [flatly, mystyles.scss]
      dark: [darkly, custom-dark.scss]
