project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  description: "Up, up and away!"
  
  twitter-card:
    creator: "@onlinecape"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "{{< fa house-user >}} Home"
      - href: about.qmd
        text: "{{< fa address-card >}} About"
      - href: CV_2022.pdf
        text: "{{< fa paperclip >}} Vitae"
      - href: mailto:shreyas.meher@utdallas.edu
        text: "{{< fa paper-plane >}} Contact"
        contents:
      - section: "{{< fa blog >}} Assignments"
        contents:
          - href: "assignments/labs/lab.qmd"
            text: Lab Assignments
          - href: "assignments/a2/a2.qmd"
            text: Assignment 2
          - href: "assignments/a3/a3.qmd"
            text: Assignment 3
      - icon: linkedin
        href: https://www.linkedin.com/in/shreyasmeher/
      - icon: twitter
        href: https://twitter.com/Onlinecape
      - icon: github
        href: https://github.com/shreyasmeher
        contents:
      - section: "{{< fa diagram-project >}} Projects"
        contents:
            - href: "projects/BLScraper/bls.html"
              text: BLScraper

  page-footer: 
    left: "@ Copyright 2023, Shreyas Meher"


format:
  html:
    theme:
      light: [flatly, mystyles.scss]
      dark: [darkly, custom-dark.scss]
      



