project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  description: "Up, up and away!"
  
  twitter-card:
    creator: "@onlinecape"
  navbar:
    title: false
    background: primary
    left:
      - href: index.qmd
        text: "{{< fa house-user >}} Home"
      - href: about.qmd
        text: "{{< fa address-card >}} About"
      - href: CV_2022.pdf
        text: "{{< fa paperclip >}} Vitae"
      - href: mailto:shreyas.meher@utdallas.edu
        text: "{{< fa paper-plane >}} Contact"
    right: 
    - icon: linkedin
      href: https://www.linkedin.com/in/shreyasmeher/
    - icon: twitter
      href: https://twitter.com/Onlinecape
    - icon: github
      href: https://github.com/shreyasmeher

  page-footer: 
    left: "@ Copyright 2023, Shreyas Meher"
  sidebar:
    pinned: true
    align: center

format:
  html:
    theme:
      light: [flatly, mystyles.scss]
      dark: [darkly, custom-dark.scss]
    css: styles.css
      



