project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: litera
      dark: cyborg
    css: styles.css

editor: visual

