project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  favicon: favicon.png
  navbar:
    title: false
    logo: favicon.png
    logo-alt: "shreyasmeher"
    right: 
      - href: index.qmd
        text: Home
      - href: CV_2022.pdf
        text: CV



format:
  html:
    theme:
      light: [flatly, mystyles.scss]
      dark: [darkly, custom-dark.scss]

freeze: true

