project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  description: "Up, up and away!""
  
  twitter-card:
    creator: "@onlinecape"
  
  navbar:
    right:
        text: Home
      - href: index.qmd
        text: CV
      - href: CV_2022.pdf
        text: Projects
        href: projects

  page-footer: 
    left: "@ Copyright 2023 Shreyas Meher."
  sidebar:
    pinned: true
    align: center

format:
  html:
      theme: cosmo
      css: styles.css
      toc: true
      



