project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  description: "Up, up and away!"
  
  twitter-card:
    creator: "@onlinecape"
    
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "{{< fa house-user >}} Home"
      - href: research.qmd
        text: "{{< fa microchip >}} Research"
      - href: CV_2023.pdf
        text: "{{< fa paperclip >}} Vitae"
      - href: mailto:shreyas.meher@utdallas.edu
        text: "{{< fa paper-plane >}} Contact"
      - icon: linkedin
        href: https://www.linkedin.com/in/shreyasmeher/
      - icon: twitter
        href: https://twitter.com/Onlinecape
      - icon: github
        href: https://github.com/shreyasmeher

  page-footer: 
    left: "© 2023 Shreyas Meher"
    
format:
  html:
    theme:
      light: [flatly, mystyles.scss]
      dark: [darkly, custom-dark.scss]
