project:
  type: website
  output-dir: docs

website:
  title: "Shreyas Meher"
  description: "Up, up and away!"
  
  twitter-card:
    creator: "@onlinecape"
    
  navbar:
    style: "sticky"
    brand:
      href: index.qmd
      text: "{{< fa house-user >}} Home"
    items:
      - section: "Main"
        items:
          - href: about.qmd
            text: "{{< fa address-card >}} About"
          - href: CV_2022.pdf
            text: "{{< fa paperclip >}} Vitae"
          - href: mailto:shreyas.meher@utdallas.edu
            text: "{{< fa paper-plane >}} Contact"
      - section: "{{< fa blog >}} Assignments"
        items:
          - href: "assignments/labs/lab.qmd"
            text: Lab Assignments
          - href: "assignments/a2/a2.qmd"
            text: Assignment 2
          - href: "assignments/a3/a3.qmd"
            text: Assignment 3
          - href: "assignments/a4/a4.qmd"
            text: Assignment 4
          - href: "assignments/a5/a5.qmd"
            text: Assignment 5
          - href: "assignments/proposal/prop-2-22-23.qmd"
            text: Project Proposal
      - section: "{{< fa diagram-project >}} Projects"
        items:
          - href: "projects/BLScraper/bls.html"
            text: BLScraper
          - href: "projects/CPU/CPU.html"
            text: CPU Usage Monitor
      - icon: github
        href: https://github.com/shreyasmeher
        aria-label: GitHub
        align: "right"

  page-footer: 
    left: "© 2023 Shreyas Meher"
    
format:
  html:
    theme:
      light: [flatly, mystyles.scss]
      dark: [darkly, custom-dark.scss]
