---
title: "About"
about:
  template: solana
  links:
    - icon: envelope
      text: Email
      href: mailto:meher@essb.eur.nl
    - icon: twitter
      text: Twitter
      href: https://twitter.com/shreyasmhr
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/shreyasmeher/
    - icon: github
      text: Github
      href: https://github.com/shreyasmeher
---

### Professionally

I am a Postdoctoral Researcher at Erasmus University Rotterdam, where I specialize in applying artificial intelligence to critical challenges in politics and governance. My current research, as part of the Horizon Europe-funded **TWIN4DEM project**, focuses on developing 'digital twins' to model and preempt threats of democratic backsliding.

This work builds on my Ph.D. in Public Policy and Political Economy from the University of Texas at Dallas. My doctoral research centered on digital censorship and political conflict, leading to contributions to computational social science through projects like the NSF-funded **ConfliBERT** initiative.

### Personally

I'm an avid football fan, rooting for Inter Milan, and a culinary enthusiast who loves exploring and creating new Dim Sum recipes.

### Education

**The University of Texas at Dallas**
Ph.D. in Public Policy & Political Economy, 2025

**The University of Texas at Dallas**
M.S. in Management, 2020

**St. Xavier's College, Mumbai**
M.A. in Public Policy, 2018

**Narsee Monjee Institute of Management Studies**
B.S. in Economics, 2016